/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Negocio.Candidato;
import Negocio.uso_Candidato;
import java.text.DecimalFormat;
import javax.swing.JLabel;

/**
 *
 * @author Daniel
 */
public class Principal extends javax.swing.JFrame {

    public Candidato c1 = new Candidato("Adan", 27, "SocioCucuta", 0, 0, 0, 0, 0, 0, 0, 0);
    public Candidato c2 = new Candidato("Eva", 27, "Unicucuta", 0, 0, 0, 0, 0, 0, 0, 0);
    public Candidato c3 = new Candidato("Samael", 27, "SuperCucuta", 0, 0, 0, 0, 0, 0, 0, 0);
    public uso_Candidato u = new uso_Candidato();
    DecimalFormat f = new DecimalFormat("#.00");
    public double pmujeres;
    public double phombre;
    public double pjoven;
    public double padulto;
    public double abuelo;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jAASLoginService1 = new org.jdesktop.swingx.auth.JAASLoginService();
        vurna = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Candidato1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        C1Influencia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombreC1 = new javax.swing.JLabel();
        Edad1 = new javax.swing.JLabel();
        Parido1 = new javax.swing.JLabel();
        costecamp1 = new javax.swing.JLabel();
        numvot1 = new javax.swing.JLabel();
        pvotos1 = new javax.swing.JLabel();
        rangoEdad = new javax.swing.JComboBox<>();
        Sexo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Genero = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        MujerPorcentaje = new javax.swing.JLabel();
        HombrePorcentaje = new javax.swing.JLabel();
        Jovenp = new javax.swing.JLabel();
        AdultoP = new javax.swing.JLabel();
        AbueloP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Candidato2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        C2Influencia = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nombreC2 = new javax.swing.JLabel();
        Edad2 = new javax.swing.JLabel();
        Parido2 = new javax.swing.JLabel();
        costecamp2 = new javax.swing.JLabel();
        numvot2 = new javax.swing.JLabel();
        pvotos2 = new javax.swing.JLabel();
        Sexo1 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rangoEdad1 = new javax.swing.JComboBox<>();
        Genero1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 37), new java.awt.Dimension(0, 37), new java.awt.Dimension(32767, 37));
        MujerPorcentaje1 = new javax.swing.JLabel();
        HombrePorcentaje1 = new javax.swing.JLabel();
        Jovenp1 = new javax.swing.JLabel();
        AdultoP1 = new javax.swing.JLabel();
        AbueloP1 = new javax.swing.JLabel();
        Candidato3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        C1Influencia2 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        nombreC3 = new javax.swing.JLabel();
        Edad3 = new javax.swing.JLabel();
        Parido3 = new javax.swing.JLabel();
        costecamp3 = new javax.swing.JLabel();
        numvot3 = new javax.swing.JLabel();
        pvotos3 = new javax.swing.JLabel();
        Sexo2 = new javax.swing.JComboBox<>();
        rangoEdad2 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Genero2 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        MujerPorcentaje2 = new javax.swing.JLabel();
        HombrePorcentaje2 = new javax.swing.JLabel();
        Jovenp2 = new javax.swing.JLabel();
        AdultoP2 = new javax.swing.JLabel();
        AbueloP2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(200, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vurna.setText("Vaciar Urna");
        vurna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vurnaActionPerformed(evt);
            }
        });
        getContentPane().add(vurna, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 100, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 60, -1));

        Candidato1.setBackground(new java.awt.Color(171, 176, 149));
        Candidato1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Candidato 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Bold ITC", 2, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        Candidato1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Candidato1ComponentAdded(evt);
            }
        });
        Candidato1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hombre (3).png"))); // NOI18N
        Candidato1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, 160));

        jButton1.setText("Votar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Candidato1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 60, 30));

        C1Influencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Radio", "Television", "Internet" }));
        Candidato1.add(C1Influencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel5.setText("Tipo de Influencia:");
        Candidato1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 10));

        jLabel6.setText("Nombre:");
        Candidato1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 10));

        jLabel7.setText("Partido:");
        Candidato1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel8.setText("Edad:");
        Candidato1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 20));

        jLabel9.setText("Coste Campaña:");
        Candidato1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel10.setText("Num de Votos:");
        Candidato1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel11.setText("% de Votos:");
        Candidato1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        nombreC1.setText("Candidato 1");
        Candidato1.add(nombreC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 60, 10));

        Edad1.setText("24");
        Edad1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Edad1ComponentAdded(evt);
            }
        });
        Candidato1.add(Edad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 10));

        Parido1.setText("parido");
        Candidato1.add(Parido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        costecamp1.setText("Coste");
        Candidato1.add(costecamp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        numvot1.setText("0 de votos");
        Candidato1.add(numvot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        pvotos1.setText("jLabel14");
        Candidato1.add(pvotos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        rangoEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18 a 30", "30 a 50", "50 a 80" }));
        Candidato1.add(rangoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        Candidato1.add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jLabel2.setText("Edad:");
        Candidato1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 10));

        jLabel3.setText("Genero:");
        Candidato1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, 10));

        jLabel28.setText(" Est. Edad:");
        Candidato1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        Genero.setText("Est. Genero:");
        Candidato1.add(Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        Candidato1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 412, 230, 0));

        MujerPorcentaje.setText("0% Mujeres");
        Candidato1.add(MujerPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        HombrePorcentaje.setText("0% Hombres");
        Candidato1.add(HombrePorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        Jovenp.setText("0% Jovenes");
        Candidato1.add(Jovenp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        AdultoP.setText("0% Adultos");
        Candidato1.add(AdultoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, 10));

        AbueloP.setText("0% Abuelos");
        Candidato1.add(AbueloP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, 10));

        getContentPane().add(Candidato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 240, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banner.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 680, 150, 20));

        Candidato2.setBackground(new java.awt.Color(171, 176, 149));
        Candidato2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Candidato 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Bold ITC", 2, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        Candidato2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Candidato2ComponentAdded(evt);
            }
        });
        Candidato2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chica (3).png"))); // NOI18N
        Candidato2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jButton3.setText("Votar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Candidato2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        C2Influencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Radio", "Television", "Internet" }));
        Candidato2.add(C2Influencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel13.setText("Tipo de Influencia:");
        Candidato2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel14.setText("Nombre:");
        Candidato2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel15.setText("Partido:");
        Candidato2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel16.setText("Edad:");
        Candidato2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel17.setText("Coste Campaña:");
        Candidato2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel18.setText("Num de Votos:");
        Candidato2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel19.setText("% de Votos:");
        Candidato2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 70, -1));

        nombreC2.setText("Candidato 1");
        Candidato2.add(nombreC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 85, -1));

        Edad2.setText("24");
        Edad2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Edad2ComponentAdded(evt);
            }
        });
        Candidato2.add(Edad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        Parido2.setText("parido");
        Candidato2.add(Parido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        costecamp2.setText("Coste");
        Candidato2.add(costecamp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        numvot2.setText("0 de votos");
        Candidato2.add(numvot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        pvotos2.setText("jLabel14");
        Candidato2.add(pvotos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        Sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        Candidato2.add(Sexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jLabel29.setText("Genero:");
        Candidato2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        jLabel30.setText("Edad:");
        Candidato2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        rangoEdad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18 a 30", "30 a 50", "50 a 80" }));
        Candidato2.add(rangoEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        Genero1.setText("Est. Edad:");
        Candidato2.add(Genero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel31.setText("Est. Genero:");
        Candidato2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        Candidato2.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        MujerPorcentaje1.setText("0% Mujeres");
        Candidato2.add(MujerPorcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        HombrePorcentaje1.setText("0% Hombres");
        Candidato2.add(HombrePorcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        Jovenp1.setText("0% Jovenes");
        Candidato2.add(Jovenp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        AdultoP1.setText("0% Adultos");
        Candidato2.add(AdultoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 10));

        AbueloP1.setText("0% Abuelos");
        Candidato2.add(AbueloP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, 10));

        getContentPane().add(Candidato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 240, 530));

        Candidato3.setBackground(new java.awt.Color(171, 176, 149));
        Candidato3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Candidato 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Bold ITC", 2, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        Candidato3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Candidato3ComponentAdded(evt);
            }
        });
        Candidato3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hombre (4).png"))); // NOI18N
        Candidato3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jButton4.setText("Votar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Candidato3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        C1Influencia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Radio", "Television", "Internet" }));
        Candidato3.add(C1Influencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel21.setText("Tipo de Influencia:");
        Candidato3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel22.setText("Nombre:");
        Candidato3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel23.setText("Partido:");
        Candidato3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel24.setText("Edad:");
        Candidato3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel25.setText("Coste Campaña:");
        Candidato3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel26.setText("Num de Votos:");
        Candidato3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel27.setText("% de Votos:");
        Candidato3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        nombreC3.setText("Candidato 1");
        Candidato3.add(nombreC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 85, -1));

        Edad3.setText("24");
        Edad3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Edad3ComponentAdded(evt);
            }
        });
        Candidato3.add(Edad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        Parido3.setText("parido");
        Candidato3.add(Parido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        costecamp3.setText("Coste");
        Candidato3.add(costecamp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        numvot3.setText("jLabel13");
        Candidato3.add(numvot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        pvotos3.setText("jLabel14");
        Candidato3.add(pvotos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        Sexo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        Candidato3.add(Sexo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        rangoEdad2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18 a 30", "30 a 50", "50 a 80" }));
        Candidato3.add(rangoEdad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel32.setText("Edad:");
        Candidato3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel33.setText("Genero:");
        Candidato3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        Genero2.setText("Est. Edad:");
        Candidato3.add(Genero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel34.setText("Est Genero:");
        Candidato3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        MujerPorcentaje2.setText("0% Mujeres");
        Candidato3.add(MujerPorcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        HombrePorcentaje2.setText("0% Hombres");
        Candidato3.add(HombrePorcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        Jovenp2.setText("0% Jovenes");
        Candidato3.add(Jovenp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        AdultoP2.setText("0% Adultos");
        Candidato3.add(AdultoP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 10));

        AbueloP2.setText("0% Abuelos");
        Candidato3.add(AbueloP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, 10));

        getContentPane().add(Candidato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 240, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Candidato1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Candidato1ComponentAdded
        // TODO add your handling code here:
        nombreC1.setText(c1.getNombre());
        Edad1.setText(c1.getEdad() + "");
        Parido1.setText(c1.getPartido());
        costecamp1.setText(c1.getCampana() + "");
        numvot1.setText(c1.getCvotos() + "");
        pvotos1.setText(c1.getPvotos() + "");


    }//GEN-LAST:event_Candidato1ComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int vf = 0;
        int edad = 0;
        int genero = 0;

        if (C1Influencia.getSelectedItem().toString() == "Television") {
            vf = 1;
        }
        if (C1Influencia.getSelectedItem().toString() == "Radio") {
            vf = 2;
        }
        if (C1Influencia.getSelectedItem().toString() == "Internet") {
            vf = 3;
        }

        if (rangoEdad.getSelectedItem().toString() == "18 a 30") {
            edad = 1;
        }
        if (rangoEdad.getSelectedItem().toString() == "30 a 50") {
            edad = 2;
        }
        if (rangoEdad.getSelectedItem().toString() == "50 a 80") {
            edad = 3;
        }

        if (Sexo.getSelectedItem().toString() == "Femenino") {
            genero = 1;
        }
        if (Sexo.getSelectedItem().toString() == "Masculino") {
            genero = 2;
        }

        u.votar(vf, c1, edad, genero);

        MujerPorcentaje.setText(f.format(u.CalularpMujer(c1)) + "% Mujeres");
        HombrePorcentaje.setText(f.format(u.CalularpHombre(c1)) + "% Hombres");
        MujerPorcentaje1.setText(f.format(u.CalularpMujer(c2)) + "% Mujeres");
        HombrePorcentaje1.setText(f.format(u.CalularpHombre(c2)) + "% Hombres");
        MujerPorcentaje2.setText(f.format(u.CalularpMujer(c3)) + "% Mujeres");
        HombrePorcentaje2.setText(f.format(u.CalularpHombre(c3)) + "% Hombres");

        Jovenp.setText(f.format(u.CalularpJoven(c1)) + "% Jovenes");
        AdultoP.setText(f.format(u.CalularpAdulto(c1)) + "% Adultos");
        AbueloP.setText(f.format(u.CalularpAbuelo(c1)) + "% Abuelos");

        Jovenp1.setText(f.format(u.CalularpJoven(c2)) + "% Jovenes");
        AdultoP1.setText(f.format(u.CalularpAdulto(c2)) + "% Adultos");
        AbueloP1.setText(f.format(u.CalularpAbuelo(c2)) + "% Abuelos");

        Jovenp2.setText(f.format(u.CalularpJoven(c3)) + "% Jovenes");
        AdultoP2.setText(f.format(u.CalularpAdulto(c3)) + "% Adultos");
        AbueloP2.setText(f.format(u.CalularpAbuelo(c3)) + "% Abuelos");

        costecamp1.setText("$ " + c1.getCampana());
        numvot1.setText(c1.getCvotos() + "");
        u.CalcularP(c1);
        pvotos1.setText(f.format(c1.getPvotos()) + " %");
        u.CalcularP(c2);
        pvotos2.setText(f.format(c2.getPvotos()) + " %");
        u.CalcularP(c3);
        pvotos3.setText(f.format(c3.getPvotos()) + " %");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void Edad1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Edad1ComponentAdded


    }//GEN-LAST:event_Edad1ComponentAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int vf = 0;
        int edad = 0;
        int genero = 0;

        if (C2Influencia.getSelectedItem().toString() == "Television") {
            vf = 1;
        }
        if (C2Influencia.getSelectedItem().toString() == "Radio") {
            vf = 2;
        }
        if (C2Influencia.getSelectedItem().toString() == "Internet") {
            vf = 3;
        }

        if (rangoEdad1.getSelectedItem().toString() == "18 a 30") {
            edad = 1;
        }
        if (rangoEdad1.getSelectedItem().toString() == "30 a 50") {
            edad = 2;
        }
        if (rangoEdad1.getSelectedItem().toString() == "50 a 80") {
            edad = 3;
        }

        if (Sexo1.getSelectedItem().toString() == "Femenino") {
            genero = 1;
        }
        if (Sexo1.getSelectedItem().toString() == "Masculino") {
            genero = 2;
        }

        u.votar(vf, c2, edad, genero);
        MujerPorcentaje.setText(f.format(u.CalularpMujer(c1)) + "% Mujeres");
        HombrePorcentaje.setText(f.format(u.CalularpHombre(c1)) + "% Hombres");
        MujerPorcentaje1.setText(f.format(u.CalularpMujer(c2)) + "% Mujeres");
        HombrePorcentaje1.setText(f.format(u.CalularpHombre(c2)) + "% Hombres");
        MujerPorcentaje2.setText(f.format(u.CalularpMujer(c3)) + "% Mujeres");
        HombrePorcentaje2.setText(f.format(u.CalularpHombre(c3)) + "% Hombres");

        Jovenp.setText(f.format(u.CalularpJoven(c1)) + "% Jovenes");
        AdultoP.setText(f.format(u.CalularpAdulto(c1)) + "% Adultos");
        AbueloP.setText(f.format(u.CalularpAbuelo(c1)) + "% Abuelos");

        Jovenp1.setText(f.format(u.CalularpJoven(c2)) + "% Jovenes");
        AdultoP1.setText(f.format(u.CalularpAdulto(c2)) + "% Adultos");
        AbueloP1.setText(f.format(u.CalularpAbuelo(c2)) + "% Abuelos");

        Jovenp2.setText(f.format(u.CalularpJoven(c3)) + "% Jovenes");
        AdultoP2.setText(f.format(u.CalularpAdulto(c3)) + "% Adultos");
        AbueloP2.setText(f.format(u.CalularpAbuelo(c3)) + "% Abuelos");

        costecamp2.setText("$ " + c2.getCampana());
        numvot2.setText(c2.getCvotos() + "");
        u.CalcularP(c1);
        pvotos1.setText(f.format(c1.getPvotos()) + " %");
        u.CalcularP(c2);
        pvotos2.setText(f.format(c2.getPvotos()) + " %");
        u.CalcularP(c3);
        pvotos3.setText(f.format(c3.getPvotos()) + " %");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void Edad2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Edad2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Edad2ComponentAdded

    private void Candidato2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Candidato2ComponentAdded
        // TODO add your handling code here:
        nombreC2.setText(c2.getNombre());
        Edad2.setText(c2.getEdad() + "");
        Parido2.setText(c2.getPartido());
        costecamp2.setText(c2.getCampana() + "");
        numvot2.setText(c2.getCvotos() + "");
        pvotos2.setText(c2.getPvotos() + "");
    }//GEN-LAST:event_Candidato2ComponentAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int vf = 0;
        int edad = 0;
        int genero = 0;

        if (C1Influencia2.getSelectedItem().toString() == "Television") {
            vf = 1;
        }
        if (C1Influencia2.getSelectedItem().toString() == "Radio") {
            vf = 2;
        }
        if (C1Influencia2.getSelectedItem().toString() == "Internet") {
            vf = 3;
        }

        if (rangoEdad2.getSelectedItem().toString() == "18 a 30") {
            edad = 1;
        }
        if (rangoEdad2.getSelectedItem().toString() == "30 a 50") {
            edad = 2;
        }
        if (rangoEdad2.getSelectedItem().toString() == "50 a 80") {
            edad = 3;
        }

        if (Sexo2.getSelectedItem().toString() == "Femenino") {
            genero = 1;
        }
        if (Sexo2.getSelectedItem().toString() == "Masculino") {
            genero = 2;
        }

        u.votar(vf, c3, edad, genero);
        MujerPorcentaje.setText(f.format(u.CalularpMujer(c1)) + "% Mujeres");
        HombrePorcentaje.setText(f.format(u.CalularpHombre(c1)) + "% Hombres");
        MujerPorcentaje1.setText(f.format(u.CalularpMujer(c2)) + "% Mujeres");
        HombrePorcentaje1.setText(f.format(u.CalularpHombre(c2)) + "% Hombres");

        MujerPorcentaje2.setText(f.format(u.CalularpMujer(c3)) + "% Mujeres");
        HombrePorcentaje2.setText(f.format(u.CalularpHombre(c3)) + "% Hombres");

        Jovenp.setText(f.format(u.CalularpJoven(c1)) + "% Jovenes");
        AdultoP.setText(f.format(u.CalularpAdulto(c1)) + "% Adultos");
        AbueloP.setText(f.format(u.CalularpAbuelo(c1)) + "% Abuelos");

        Jovenp1.setText(f.format(u.CalularpJoven(c2)) + "% Jovenes");
        AdultoP1.setText(f.format(u.CalularpAdulto(c2)) + "% Adultos");
        AbueloP1.setText(f.format(u.CalularpAbuelo(c2)) + "% Abuelos");

        Jovenp2.setText(f.format(u.CalularpJoven(c3)) + "% Jovenes");
        AdultoP2.setText(f.format(u.CalularpAdulto(c3)) + "% Adultos");
        AbueloP2.setText(f.format(u.CalularpAbuelo(c3)) + "% Abuelos");

        costecamp3.setText("$ " + c3.getCampana());
        numvot3.setText(c3.getCvotos() + "");
        u.CalcularP(c1);
        pvotos1.setText(f.format(c1.getPvotos()) + " %");
        u.CalcularP(c2);
        pvotos2.setText(f.format(c2.getPvotos()) + " %");
        u.CalcularP(c3);
        pvotos3.setText(f.format(c3.getPvotos()) + " %");


    }//GEN-LAST:event_jButton4ActionPerformed

    private void Edad3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Edad3ComponentAdded
       
    }//GEN-LAST:event_Edad3ComponentAdded

    private void Candidato3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Candidato3ComponentAdded
       

        nombreC3.setText(c3.getNombre());
        Edad3.setText(c3.getEdad() + "");
        Parido3.setText(c3.getPartido());
        costecamp3.setText(c3.getCampana() + "");
        numvot3.setText(c3.getCvotos() + "");
        pvotos3.setText(c3.getPvotos() + "");
        
    }//GEN-LAST:event_Candidato3ComponentAdded

    private void vurnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vurnaActionPerformed
        // TODO add your handling code here:
        c1.setCampana(0);
        c1.setCvotos(0);
        c1.setPvotos(0);
        c1.setVotosabuelo(0);
        c1.setVotosadulto(0);
        c1.setVotoshombre(0);
        c1.setVotosjoven(0);
        c1.setVotosmujer(0);

        c2.setCampana(0);
        c2.setCvotos(0);
        c2.setPvotos(0);
        c2.setVotosabuelo(0);
        c2.setVotosadulto(0);
        c2.setVotoshombre(0);
        c2.setVotosjoven(0);
        c2.setVotosmujer(0);

        c3.setCampana(0);
        c3.setCvotos(0);
        c3.setPvotos(0);
        c3.setVotosabuelo(0);
        c3.setVotosadulto(0);
        c3.setVotoshombre(0);
        c3.setVotosjoven(0);
        c3.setVotosmujer(0);
        u.setTotalv(0);
        u.setTotalvabuelo(0);
        u.setTotalvadulto(0);
        u.setTotalvhombre(0);
        u.setTotalvjoven(0);
        u.setTotalvmujer(0);

        costecamp1.setText("$0");
        numvot1.setText("0");
        pvotos1.setText("0%");
        costecamp3.setText("$0");
        numvot3.setText("0");
        pvotos3.setText("0%");
        costecamp2.setText("$0");
        numvot2.setText("0");
        pvotos2.setText("0%");

        MujerPorcentaje.setText("0% Mujeres");
        MujerPorcentaje1.setText("0% Mujeres");
        MujerPorcentaje2.setText("0% Mujeres");

        HombrePorcentaje.setText("0% Hombres");
        HombrePorcentaje1.setText("0% Hombres");
        HombrePorcentaje2.setText("0% Hombres");
        
        AdultoP.setText("0% Adultos");
        AdultoP1.setText("0% Adultos");
        AdultoP2.setText("0% Adultos");
        
        Jovenp.setText("0% Jovenes");
        Jovenp1.setText("0% Jovenes");
        Jovenp2.setText("0% Jovenes");
        
        AbueloP.setText("0% Abuelos");
        AbueloP1.setText("0% Abuelos");
        AbueloP2.setText("0% Abuelos");

    }//GEN-LAST:event_vurnaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AbueloP;
    private javax.swing.JLabel AbueloP1;
    private javax.swing.JLabel AbueloP2;
    private javax.swing.JLabel AdultoP;
    private javax.swing.JLabel AdultoP1;
    private javax.swing.JLabel AdultoP2;
    private javax.swing.JComboBox<String> C1Influencia;
    private javax.swing.JComboBox<String> C1Influencia2;
    private javax.swing.JComboBox<String> C2Influencia;
    private javax.swing.JPanel Candidato1;
    private javax.swing.JPanel Candidato2;
    private javax.swing.JPanel Candidato3;
    private javax.swing.JLabel Edad1;
    private javax.swing.JLabel Edad2;
    private javax.swing.JLabel Edad3;
    private javax.swing.JLabel Genero;
    private javax.swing.JLabel Genero1;
    private javax.swing.JLabel Genero2;
    private javax.swing.JLabel HombrePorcentaje;
    private javax.swing.JLabel HombrePorcentaje1;
    private javax.swing.JLabel HombrePorcentaje2;
    private javax.swing.JLabel Jovenp;
    private javax.swing.JLabel Jovenp1;
    private javax.swing.JLabel Jovenp2;
    private javax.swing.JLabel MujerPorcentaje;
    private javax.swing.JLabel MujerPorcentaje1;
    private javax.swing.JLabel MujerPorcentaje2;
    private javax.swing.JLabel Parido1;
    private javax.swing.JLabel Parido2;
    private javax.swing.JLabel Parido3;
    private javax.swing.JComboBox<String> Sexo;
    private javax.swing.JComboBox<String> Sexo1;
    private javax.swing.JComboBox<String> Sexo2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel costecamp1;
    private javax.swing.JLabel costecamp2;
    private javax.swing.JLabel costecamp3;
    private javax.swing.Box.Filler filler1;
    private org.jdesktop.swingx.auth.JAASLoginService jAASLoginService1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nombreC1;
    private javax.swing.JLabel nombreC2;
    private javax.swing.JLabel nombreC3;
    private javax.swing.JLabel numvot1;
    private javax.swing.JLabel numvot2;
    private javax.swing.JLabel numvot3;
    private javax.swing.JLabel pvotos1;
    private javax.swing.JLabel pvotos2;
    private javax.swing.JLabel pvotos3;
    private javax.swing.JComboBox<String> rangoEdad;
    private javax.swing.JComboBox<String> rangoEdad1;
    private javax.swing.JComboBox<String> rangoEdad2;
    private javax.swing.JButton vurna;
    // End of variables declaration//GEN-END:variables
}
